name: Bump Homebrew cask on release
on:
  repository_dispatch:
    types: [new-release]

jobs:
  bump-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get release info
        id: rel
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
          
          # Download and get SHA
          FILE="BoomSnap-${VERSION#v}-arm64-mac.zip"
          curl -L -o "$FILE" \
            "https://github.com/olekristianbe/boomsnap/releases/download/${VERSION}/${FILE}"
          SHASUM=$(shasum -a 256 "$FILE" | awk '{print $1}')
          echo "SHA=${SHASUM}" >> $GITHUB_ENV
          
      - name: Update cask
        run: |
          sed -i 's/version ".*"/version "'${VERSION}'"/' Casks/boomsnap.rb
          sed -i 's/sha256 .*/sha256 "'${SHA}'"/' Casks/boomsnap.rb
          
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump BoomSnap to ${VERSION}"